config/routes.rb
Cse280::Application.routes.draw do
  
  resources :user_sessions

  resources :users
  
  get "register" => "users#new"
  get "login" => "user_sessions#new"
  get "logout" => "user_sessions#destroy"
  
  get "restaurants" => "restaurant#index"
   get "restaurant" => "restaurant#index"

  get "restaurant/preview"

  root :to => "home#index"
   
  get "about" => "home#about"
  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
		@home_banner  = true
  end

  def about
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<div id="AboutUsDiv">
	<h1>About Us</h1>
	<h2>Who We Are</h2>
		<p>We Deliver is a company built by six college students/ entrepreneurs/ problem-solvers.
		   Our team consists of Nick Land, Sean Scott, Anthony Roethemeyer, Yaseen Syed, Joe Niksa and Zach Walters.
		   Each team member is dedicated to delivering a quality experience.
		</p>
	<h2>What We Do</h2>
		<p> Here at We Deliver, we like to think that we're solving a problem. 
			The problem? Being able to eat restaurant quality food without going to a restaurant.
			Lets's face it, everyone tends to be a little lazy or maybe they're not <i>ahem</i> good at cooking.
			That's where We Deliver comes in to play. You tell us what you want to eat, we'll get it for from top-notch 
			restaurants in the Rochester Hills area. Our business is to bring the best of Rochester to your table.
			
		
		</p>
	<table id="pics">
	<tr>
	<td><%=image_tag "home/about/Joe.jpg", :id => "image"%></td>
	<td><%=image_tag "home/about/Zach.jpg", :id => "image"%></td>
	</tr>
	<tr>
	<td id="name"><center>Joe</center></td>
	<td id="name"><center>Zach</center></td>
	</tr>
	<tr>
	<td><%=image_tag "home/about/Shawn.jpg", :id => "image"%></td>
	<td><%=image_tag "home/about/Nick.jpg", :id => "image"%></td>
	</tr>
	<tr>
	<td id="name"><center>Shawn</center></td>
	<td id="name"><center>Nick</center></td>
	</tr>
	<tr>
	<td><%=image_tag "home/about/Anthony.jpg", :id => "image"%></td>
	<td><%=image_tag "home/about/Anthony.jpg", :id => "image"%></td>
	</tr>
	<tr>
	<td id="name"><center>Anthony</center></td>
	<td id="name"><center>Yaseen</center></td>
	</tr>
	</table>
</div>

app/views/home/index.html.erb
<div class="chairs">
		<%= link_to( image_tag('home/landing/chair_about.png',  :id => "chair"), about_path)%>
		<%=link_to image_tag('home/landing/chair_range.png', :id => "chair"), '#'%>
		<%=link_to image_tag('home/landing/chair_restaurants.png', :id => "chair"), restaurants_path%>
</div>

<div>
	<%=image_tag 'home/landing/chair_table.png', :class => 'table' %>
</div>