config/routes.rb
Cse280::Application.routes.draw do
  
  resources :user_sessions

  resources :users
  
  get "register" => "users#new"
  get "login" => "user_sessions#new"
  get "logout" => "user_sessions#destroy"
  
  get "restaurants" => "restaurant#index"
   get "restaurant" => "restaurant#index"

  get "restaurant/preview"

  root :to => "home#index"
   
  get "about" => "home#about"
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>We Deliver</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>	
	
		<% flash.each do |name, msg| %>
			<div>
			<% if msg.is_a?(String) %>
			<%=content_tag :div, msg, :id => "flash_#{name}"%>
			<%end%>
			</div>
		<%end%>
	<% if @home_banner %>
	<% else %>
	<div id="MenuBarDiv">
		<ul class="MenuBar">
			<li class="listStyle"><%=link_to "HOME", root_path, :class => "menuBarLinks"%></li>
			<li class="listStyle"> <%=link_to "ABOUT", about_path, :class => "menuBarLinks"%>
			<li class="listStyle"><%=link_to "RESTARUANTS", restaurant_path, :class => "menuBarLinks"%> </li>
			
			<%=link_to image_tag('home/landing/Logo.png'), root_path, :id => "WeDeliverLogo" %>
			
			<li class="listStyle"><%=link_to "RANGE", '#', :class => "menuBarLinks"%> </li>
			<li class="listStyle"> <%=link_to "CONTACT US", '#', :class => "menuBarLinks"%> </li>
			<li class="listStyle"><%=link_to "ORDER", '#', :class => "menuBarLinks"%>  </li>
		</ul>
	</div>
	<% end %>



	
	<div class = "login">
		<ul>
		<%if current_user %>
			<li> <%=link_to "Edit Profile", edit_user_path(:current), :id => "login" %> </li>
			<li> | </li>
			<li> <%=link_to "Logout", logout_path, :id => "login" %></li>
		<% else %>
			<li> <%= link_to "Register", register_path, :id => "login" %></li>
			<li> | </li>
			<li> <%= link_to "Login", login_path, :id => "login" %></li>
		<% end %>
		
		</ul>
	</div>


<div class = "container">
	<%= yield %>
</div>


<div id="BottomBarDiv">
	<ul class="MenuBar">
		<li class="listStyle"> <a class= "menuBarLinks" href="About.html">About  |</a>  </li>
		<li class="listStyle"> <a class= "menuBarLinks" href="Adverstise.html">Advertise  |</a> </li>
		<li class="listStyle"> <a class= "menuBarLinks" href="Contact.html">Contact Us  |</a> </li>
		<li class="listStyle"> <a class= "menuBarLinks" href="Terms.html">Terms of Service  |</a> </li>
		<li class="listStyle"> <a class= "menuBarLinks" href="Jobs.html">Jobs</a> </li>
	</ul>
</div>

</body>
</html>